set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports z]
set_property PACKAGE_PIN V16 [get_ports A]
set_property PACKAGE_PIN V17 [get_ports B]
set_property PACKAGE_PIN P1 [get_ports c]
set_property PACKAGE_PIN R2 [get_ports clk]
set_property PACKAGE_PIN L1 [get_ports z]

create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports La]
set_property IOSTANDARD LVCMOS33 [get_ports Lb]
set_property IOSTANDARD LVCMOS33 [get_ports Lclk]
set_property PACKAGE_PIN E19 [get_ports La]
set_property PACKAGE_PIN U16 [get_ports Lb]
set_property PACKAGE_PIN N3 [get_ports Lclk]
